#!/usr/bin/env node

/* ** Main Program **

    @description - This program may be configured using parameter options below
    Makes it simple to deploy your contracts to your network of choice
    run with --help
*/
const program = require(`commander`)
const { dapploy } = require(`./src/deployDapp`)
const { parseConfig, initConfig } = require(`./src/configParser`)
const { buildAndDeployTemplate, supported } = require(`./src/deployTemplate`)
const defaultConfig = `.dapploy`
program
  .version(`0.1.0`)
  .option(`-t, --projectDir <dir>`, `Truffle Project Directory`)
  .option(`-n, --network <network>`, `Deploy to network`)
  .option(`-c, --config <config>`, `Config file`, defaultConfig)
  .option(`-o, --contractOutput <dir>`, `Contract Output Directory`)
  .option(`-x, --excludeContracts [Contract1,Contract2]`, `Exclude contracts from the web3 interface (files are still copied)`)
  .option(`-a, --includeContracts [Contract1,Contract2]`, `Include contracts from the web3 interface (files are still copied)`)
  .option(`-l, --clean`, `Clean contracts before migrating`)
  .option(`-r, --remoteOnly`, `Only copy contracts remote`)
  .option(`-p, --pinToIpfs`, `Pin contracts to IPFS for remote access`)
  .option(`-k, --bucketName`, `Do remote copy of ABI to aws bucket (make sure to setup ~/.aws)`)
  .option(`-y, --copyOnly`, `Only do folder copy and S3 copy`)
  .option(`-i, --init`, `Add default config file to current directory`)

let execute = [p => dapploy(p)]
program.command(`init [dir]`)
  .description(`Configure a new truffle project from scratch`)
  .option(`-g, --configOnly`, `Create dapploy config file in current directory`)
  .option(`-s, --specifyContract [contract]`, `Which type of project to create.\n\t\t\t\t\tSupporting: ${supported}`, `ERC20`)
  .action((dir, cmd) => {
    // console.log("HERE", program, cmd)
    program.initPath = dir || `./`
    program.specifyContract = cmd.specifyContract
    if (cmd.configOnly) {
      execute = [p => initConfig(p)]
    } else {
      execute = [p => buildAndDeployTemplate(p)]
    }
  })


program.parse(process.argv)

async function asyncForEach (array, callback) {
  for (let index = 0; index < array.length; index++) {
    await callback(array[index], index, array)
  }
}

try {
  parseConfig(program)
} catch (err) {
  console.log(err)
  process.exit(1)
}
(async () => {
  asyncForEach(execute, async (exe) => {
    // console.log(`Running command`, exe)
    try {
      await exe(program)
    } catch (err) {
      console.log(err)
      process.exit(1)
      throw err
    }
  })
})()
